from datetime import datetime
import json

import bcrypt
from werkzeug.security import check_password_hash

from .extensions import db


class User(db.Model):
    """Application user with PIN authentication."""

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(255), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    # Backwards-compatible column for earlier password-based auth.
    password_hash = db.Column(db.String(255), nullable=False)
    pin_hash = db.Column(db.String(255), nullable=False)
    details = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    messages = db.relationship(
        "Message", back_populates="user", cascade="all, delete-orphan"
    )
    progress_updates = db.relationship(
        "Progress", back_populates="user", cascade="all, delete-orphan"
    )
    questionnaire_responses = db.relationship(
        "QuestionnaireResponse", back_populates="user", cascade="all, delete-orphan"
    )

    def set_pin(self, raw_pin: str) -> None:
        """Hash and store the provided PIN."""
        hashed = bcrypt.hashpw(raw_pin.encode("utf-8"), bcrypt.gensalt())
        hashed_value = hashed.decode("utf-8")
        self.pin_hash = hashed_value
        # Keep legacy column populated to satisfy older schemas.
        self.password_hash = hashed_value

    def check_pin(self, raw_pin: str) -> bool:
        """Validate a raw PIN against the stored hash."""
        if self.pin_hash:
            try:
                return bcrypt.checkpw(raw_pin.encode("utf-8"), self.pin_hash.encode("utf-8"))
            except ValueError:
                # Legacy hashes may be generated by Werkzeug (e.g., scrypt/pbkdf2).
                return check_password_hash(self.pin_hash, raw_pin)
        if self.password_hash:
            try:
                return bcrypt.checkpw(raw_pin.encode("utf-8"), self.password_hash.encode("utf-8"))
            except ValueError:
                # Keep backward compatibility with pre-bcrypt stored hashes.
                return check_password_hash(self.password_hash, raw_pin)
        return False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "full_name": self.full_name,
            "username": self.username,
            "details": self.details,
            "created_at": self.created_at.isoformat(),
        }


class Message(db.Model):
    """Individual chat messages between a user and the assistant."""

    __tablename__ = "messages"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    role = db.Column(db.String(32), nullable=False)  # "user" or "assistant"
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.CheckConstraint("role IN ('user','assistant')", name="ck_messages_role"),
        db.Index("ix_messages_user_id", "user_id"),
        db.Index("ix_messages_created_at", "created_at"),
    )

    user = db.relationship("User", back_populates="messages")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "role": self.role,
            "content": self.content,
            "created_at": self.created_at.isoformat(),
        }


class Progress(db.Model):
    """Milestones or learning progress entries recorded per user."""

    __tablename__ = "progress"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    milestone = db.Column(db.String(255), nullable=False)
    notes = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    user = db.relationship("User", back_populates="progress_updates")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "milestone": self.milestone,
            "notes": self.notes,
            "created_at": self.created_at.isoformat(),
        }


class QuestionnaireResponse(db.Model):
    """Stored onboarding questionnaire responses per user."""

    __tablename__ = "questionnaire_responses"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    answers_json = db.Column(db.Text, nullable=False)
    recommendation_text = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.Index("ix_questionnaire_user_id", "user_id"),
        db.Index("ix_questionnaire_created_at", "created_at"),
    )

    user = db.relationship("User", back_populates="questionnaire_responses")

    def to_dict(self) -> dict:
        try:
            answers = json.loads(self.answers_json) if self.answers_json else {}
        except json.JSONDecodeError:
            answers = {}
        return {
            "id": self.id,
            "user_id": self.user_id,
            "answers": answers,
            "recommendation_text": self.recommendation_text,
            "created_at": self.created_at.isoformat(),
        }


class AppDoc(db.Model):
    """Structured application metadata sourced from the Endless OS app list."""

    __tablename__ = "app_docs"

    id = db.Column(db.Integer, primary_key=True)
    app_name = db.Column(db.Text, nullable=False)
    category = db.Column(db.Text, nullable=True)
    requires_internet = db.Column(db.Boolean, nullable=True)
    cost = db.Column(db.Text, nullable=True)
    swahili_support = db.Column(db.Boolean, nullable=True)
    keep_installed = db.Column(db.Text, nullable=True)
    impact = db.Column(db.Text, nullable=True)
    description = db.Column(db.Text, nullable=True)
    source = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.Index("ix_app_docs_app_name", "app_name"),
        db.Index("ix_app_docs_category", "category"),
        db.Index("ix_app_docs_impact", "impact"),
    )

    embeddings = db.relationship(
        "AppEmbedding",
        back_populates="app_doc",
        cascade="all, delete-orphan",
    )


class AppEmbedding(db.Model):
    """Stored embedding vectors for app records."""

    __tablename__ = "app_embeddings"

    id = db.Column(db.Integer, primary_key=True)
    app_doc_id = db.Column(db.Integer, db.ForeignKey("app_docs.id"), nullable=False)
    embedding_json = db.Column(db.Text, nullable=False)
    embedding_model = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (db.Index("ix_app_embeddings_app_doc_id", "app_doc_id"),)

    app_doc = db.relationship("AppDoc", back_populates="embeddings")
